# Dataset
IndexPath : '/Users/wzehui/Documents/MA/Daten/index/Tenor.csv'
FilePath : '/Users/wzehui/Documents/MA/Daten/quellcode/sounddb/'
DataRepeat : 0 # the Time of repeating the Training data to enlarge the dataset
TestSplitRate : 0.1
ValSplitRate : 0.05 # how many training data is regarded as validation data
FeatureExtraction : False

# Neural Network
lSave : True
DataPath : '/Users/wzehui/Documents/MA/Daten/index/train+test+val_index'
lTrain : True
BatchSize : 32
lr : 0.001
epoch : 100
BestModelPath : '/Users/wzehui/Documents/MA/Model/bestModel'

# Random Forest
FeaturePath : '/Users/wzehui/Documents/MA/Daten/feature/feature_T.csv'
# FeatureSelection : [0] # print data name for reproducible
FeatureSelection : [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] # range from 3-16, detail definitions seen Feature Preprocessing.py
RandomState : 55
BestParamPath : '/Users/wzehui/Documents/MA/Model/bestParameter.txt'
