# Dataset
IndexPath : '/Users/wzehui/Documents/MA/Daten/index/Tenor.csv'
FilePath : '/Users/wzehui/Documents/MA/Daten/quellcode/sounddb/'
FeaturePath : '/Users/wzehui/Documents/MA/Daten/quellcode/sounddb/feature_T.csv'
DataRepeat : 0 # the Time of repeating the Training data to enlarge the dataset
TestSplitRate : 0.1
ValSplitRate : 0.05 # how many training data is regarded as validation data
FeatureExtraction : False
FeatureSelection : [5, 7, 8] # range from 3-17, detail definitions seen FeaturePreprocessing.py

# Training
lSave : True
DataPath : '/Users/wzehui/Documents/MA/Daten/index/train+test+val_index'
lTrain : True
BatchSize : 32
lr : 0.001
epoch : 100
BestModelPath : '/Users/wzehui/Documents/MA/Model/bestModel'