# Dataset
IndexPath : '/Users/wzehui/Documents/MA/Daten/index/index.csv'
FilePath : '/Users/wzehui/Documents/MA/Daten/quellcode/sounddb/'
FeaturePath : '/Users/wzehui/Documents/MA/Daten/quellcode/sounddb/feature.csv'
TrainSplitRate : [0, 0.9]
TestSplitRate : [0.9, 0.95]
ValSplitRate : [0.95, 1] # how many total data is regarded as validation data
FeatureExtraction : False
FeatureSelection : [5, 7, 8] # range from 3-17, detail definitions seen FeaturePreprocessing.py

# Training
lTrain : False
BatchSize : 32
lr : 0.01
epoch : 10
BestModelPath : '/Users/wzehui/Documents/MA/Model/bestModel'