# Dataset
IndexPath : '/Users/wzehui/Documents/MA/Daten/index/index.csv'
FilePath : '/Users/wzehui/Documents/MA/Daten/quellcode/sounddb/'
FeaturePath : '/Users/wzehui/Documents/MA/Daten/quellcode/sounddb/feature.csv'
DataRepeat : 5 # the Time of repeating the Training data to enlarge the dataset
TestSplitRate : 0.05
ValSplitRate : 0.05 # how many training data is regarded as validation data
FeatureExtraction : False
FeatureSelection : [5, 7, 8] # range from 3-17, detail definitions seen FeaturePreprocessing.py

# Training
lTrain : True
BatchSize : 32
lr : 0.0001
epoch : 10
BestModelPath : '/Users/wzehui/Documents/MA/Model/bestModel'