# Dataset
IndexPath : '/Users/wzehui/Documents/MA/Daten/index/index.csv'
FilePath : '/Users/wzehui/Documents/MA/Daten/quellcode/sounddb/'
FeaturePath : '/Users/wzehui/Documents/MA/Daten/quellcode/sounddb/feature.csv'
TrainSplitRate : 0.9
TestSplitRate : 0.1
FeatureExtraction : False
FeatureSelection : [5, 7, 8] # range from 3-17, detail definitions seen FeaturePreprocessing.py

# Training
lTrain : True
BatchSize : 3
lr : 0.01
epoch : 10
BestModelPath : '/Users/wzehui/Documents/MA/Model/bestModel'